version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: book-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookdb  # Changed from realestate to bookdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy  # Wait until PostgreSQL is healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bookdb  # Changed to bookdb
      DB_USER: postgres
      DB_PASS: admin
    volumes:
      - ./data:/app/data

volumes:
  pgdata: {}
